import { WarningIcon as PhosphorWarningIcon } from '@phosphor-icons/react/dist/csr/Warning';
import { LockIcon as PhosphorLockIcon } from '@phosphor-icons/react/dist/csr/Lock';
import { ShareNetworkIcon as PhosphorShareNetworkIcon } from '@phosphor-icons/react/dist/csr/ShareNetwork';
import { DesktopIcon as PhosphorDesktopIcon } from '@phosphor-icons/react/dist/csr/Desktop';
import { MoonIcon as PhosphorMoonIcon } from '@phosphor-icons/react/dist/csr/Moon';
import { SunIcon as PhosphorSunIcon } from '@phosphor-icons/react/dist/csr/Sun';
import { XIcon as PhosphorXIcon } from '@phosphor-icons/react/dist/csr/X';
import { PaperPlaneRightIcon as PhosphorPaperPlaneRightIcon } from '@phosphor-icons/react/dist/csr/PaperPlaneRight';
import { PencilSimpleIcon as PhosphorPencilSimpleIcon } from '@phosphor-icons/react/dist/csr/PencilSimple';
import { QuotesIcon as PhosphorQuotesIcon } from '@phosphor-icons/react/dist/csr/Quotes';
import { DotsThreeIcon as PhosphorDotsThreeIcon } from '@phosphor-icons/react/dist/csr/DotsThree';
import { CheckIcon as PhosphorCheckIcon } from '@phosphor-icons/react/dist/csr/Check';
import { TrashIcon as PhosphorTrashIcon } from '@phosphor-icons/react/dist/csr/Trash';
import { CopyIcon as PhosphorCopyIcon } from '@phosphor-icons/react/dist/csr/Copy';
import { CaretDownIcon as PhosphorCaretDownIcon } from '@phosphor-icons/react/dist/csr/CaretDown';
import { CaretRightIcon as PhosphorCaretRightIcon } from '@phosphor-icons/react/dist/csr/CaretRight';
import { CaretLeftIcon as PhosphorCaretLeftIcon } from '@phosphor-icons/react/dist/csr/CaretLeft';
import { MagnifyingGlassIcon as PhosphorMagnifyingGlassIcon } from '@phosphor-icons/react/dist/csr/MagnifyingGlass';
import { DownloadIcon as PhosphorDownloadIcon } from '@phosphor-icons/react/dist/csr/Download';
import { GearIcon as PhosphorGearIcon } from '@phosphor-icons/react/dist/csr/Gear';
import { CornersOutIcon as PhosphorCornersOutIcon } from '@phosphor-icons/react/dist/csr/CornersOut';
import { CornersInIcon as PhosphorCornersInIcon } from '@phosphor-icons/react/dist/csr/CornersIn';
import { ArrowsCounterClockwiseIcon as PhosphorArrowsCounterClockwiseIcon } from '@phosphor-icons/react/dist/csr/ArrowsCounterClockwise';
import { EyeIcon as PhosphorEyeIcon } from '@phosphor-icons/react/dist/csr/Eye';
import { EyeSlashIcon as PhosphorEyeSlashIcon } from '@phosphor-icons/react/dist/csr/EyeSlash';
import { UserIcon as PhosphorUserIcon } from '@phosphor-icons/react/dist/csr/User';
import { ChatCircleIcon as PhosphorChatCircleIcon } from '@phosphor-icons/react/dist/csr/ChatCircle';
import { FileTextIcon as PhosphorFileTextIcon } from '@phosphor-icons/react/dist/csr/FileText';
import { MagicWandIcon as PhosphorMagicWandIcon } from '@phosphor-icons/react/dist/csr/MagicWand';
import { PlusIcon as PhosphorPlusIcon } from '@phosphor-icons/react/dist/csr/Plus';
import { UploadIcon as PhosphorUploadIcon } from '@phosphor-icons/react/dist/csr/Upload';
import { GithubLogoIcon as PhosphorGithubLogoIcon } from '@phosphor-icons/react/dist/csr/GithubLogo';
import { TextAaIcon as PhosphorTextAaIcon } from '@phosphor-icons/react/dist/csr/TextAa';
import { TextTIcon as PhosphorTextTIcon } from '@phosphor-icons/react/dist/csr/TextT';
import { CheckerboardIcon as PhosphorCheckerboardIcon } from '@phosphor-icons/react/dist/csr/Checkerboard';
import { forwardRef } from 'react';
import type { Icon as PhosphorIcon, IconProps, IconWeight } from '@phosphor-icons/react/dist/lib/types';

function withDefaults(Icon: PhosphorIcon, weight: IconWeight = 'regular') {
  return forwardRef<SVGSVGElement, IconProps>(function WrappedIcon(props, ref) {
    return <Icon ref={ref} size="1em" weight={weight} aria-hidden="true" {...props} />;
  });
}

export const ExclamationTriangleIcon = withDefaults(PhosphorWarningIcon);
export const LockClosedIcon = withDefaults(PhosphorLockIcon);
export const Share2Icon = withDefaults(PhosphorShareNetworkIcon);
export const DesktopIcon = withDefaults(PhosphorDesktopIcon);
export const MoonIcon = withDefaults(PhosphorMoonIcon);
export const SunIcon = withDefaults(PhosphorSunIcon);
export const Cross2Icon = withDefaults(PhosphorXIcon);
export const PaperPlaneIcon = withDefaults(PhosphorPaperPlaneRightIcon);
export const Pencil2Icon = withDefaults(PhosphorPencilSimpleIcon);
export const QuoteIcon = withDefaults(PhosphorQuotesIcon);
export const DotsHorizontalIcon = withDefaults(PhosphorDotsThreeIcon);
export const CheckIcon = withDefaults(PhosphorCheckIcon);
export const TrashIcon = withDefaults(PhosphorTrashIcon);
export const CopyIcon = withDefaults(PhosphorCopyIcon);
export const ChevronDownIcon = withDefaults(PhosphorCaretDownIcon);
export const ChevronRightIcon = withDefaults(PhosphorCaretRightIcon);
export const ChevronLeftIcon = withDefaults(PhosphorCaretLeftIcon);
export const MagnifyingGlassIcon = withDefaults(PhosphorMagnifyingGlassIcon);
export const DownloadIcon = withDefaults(PhosphorDownloadIcon);
export const GearIcon = withDefaults(PhosphorGearIcon);
export const EnterFullScreenIcon = withDefaults(PhosphorCornersOutIcon);
export const ExitFullScreenIcon = withDefaults(PhosphorCornersInIcon);
export const UpdateIcon = withDefaults(PhosphorArrowsCounterClockwiseIcon);
export const EyeOpenIcon = withDefaults(PhosphorEyeIcon);
export const EyeNoneIcon = withDefaults(PhosphorEyeSlashIcon);
export const PersonIcon = withDefaults(PhosphorUserIcon);
export const ChatBubbleIcon = withDefaults(PhosphorChatCircleIcon);
export const FileTextIcon = withDefaults(PhosphorFileTextIcon);
export const MagicWandIcon = withDefaults(PhosphorMagicWandIcon);
export const PlusIcon = withDefaults(PhosphorPlusIcon);
export const UploadIcon = withDefaults(PhosphorUploadIcon);
export const GitHubLogoIcon = withDefaults(PhosphorGithubLogoIcon);
export const LetterCaseToggleIcon = withDefaults(PhosphorTextAaIcon);
export const TokensIcon = withDefaults(PhosphorTextTIcon);
export const TransparencyGridIcon = withDefaults(PhosphorCheckerboardIcon);
